language: "English (United States)"
review:
  enabled: true
  tone: "informal"
  path-instructions:
    - path: "**/*.tsx"
      instruction: >
        Review the Typescript code against the AirBnb Typescript style guide and point out any mismatches.
