language: "English (United States)"
review:
  enabled: true
  tone: "informal"
  allow:
    pull-requests:
      authors-only: true
  path-based-instructions:
    - path: "**/*.js"
      instructions: >
        Review the JavaScript code against the AirBnb JavaScript style guide and point out any mismatches.
