language: "English (United States)"
review:
  enabled: true
  tone: "informal"
  path-based-instructions:
    - path: "**/*.tsx"
      instructions: >
        Review the Typescript code against the AirBnb Typescript style guide and point out any mismatches. Reply with CAPITALIZED comments.
